# Use the official PostgreSQL image as the base image
FROM postgres:11

# Environment variables for PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=Welcome01
ENV POSTGRES_DB=mydatabase

# Expose the port PostgreSQL runs on
EXPOSE 5432

# Optional: Add custom initialization scripts if needed
# COPY init.sql /docker-entrypoint-initdb.d/
