apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { { include "database.fullname" . } }
  labels: { { - include "database.labels" . | nindent 4 } }
spec:
  serviceName: { { include "database.fullname" . } }
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels: { { - include "database.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "database.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["{{ .Values.persistence.accessMode }}"]
        resources:
          requests:
            storage: { { .Values.persistence.size } }
